attention:
  embed_dim: 64
  num_heads: 8
environment:
  map_size:
  - 50
  - 50
  num_agents: 5
experiment:
  device: cuda
hyperparameters:
  communication_period:
  - 5
  learning_rate:
  - 0.001
  train_networks: true
  training_frequency: 10
pheromone:
  decay_rate: 0.9
  dimensions:
    behavior: 6
    context: 6
    emotion: 6
    social: 6
  lifecycle:
    max_lifetime_seconds: 100
    min_magnitude_threshold: 0.01
