ablation_study:
  disable_attention_routing: false
  disable_behavior_dimension: false
  disable_context_dimension: false
  disable_emotion_dimension: false
  disable_pheromone_decay: false
  disable_social_dimension: false
attention:
  embed_dim: 64
  num_heads: 8
  topology_type: full
environment:
  map_size:
  - 50
  - 50
  max_timesteps: 1000
  num_agents: 10
experiment:
  device: cuda:0
  log_dir: results/
  name: DigitalPheromoneMAS_MainExperiment
  save_interval: 500
hyperparameters:
  alpha:
  - 0.2
  - 0.3
  - 0.4
  batch_size:
  - 16
  - 32
  beta:
  - 0.2
  - 0.3
  - 0.4
  communication_period:
  - 1
  - 2
  - 3
  learning_rate:
  - 0.001
  - 0.0005
  train_networks: true
  training_frequency: 10
memory_management:
  cleanup_threshold_percent: 80.0
  max_memory_percent: 85.0
  memory_monitor_interval: 50
  warning_memory_percent: 75.0
models:
  baseline_decay_rate: 0.1
  baseline_diffusion_rate: 0.2
  max_agents: 500
  track_information_loss: true
  use_2d_pheromone: true
  use_centralized: true
  use_proposed: true
  use_rule_based: true
monitoring:
  log_frequency: 100
  track_agent_cooperation: true
  track_attention_entropy: true
  track_communication_overhead: true
  track_computation_overhead: true
  track_environmental_adaptation: true
  track_information_transfer_efficiency: true
  track_learning_convergence: true
  track_network_load: true
  track_pheromone_diffusion_rate: true
  track_social_network_density: true
  use_wandb: true
pheromone:
  decay_rate: 0.98
  dimensions:
    behavior: 4
    context: 5
    emotion: 5
    social: 10
  lifecycle:
    max_lifetime_seconds: 120.0
    min_magnitude_threshold: 0.01
ray_config:
  dashboard_host: 0.0.0.0
  dashboard_port: 8265
  memory: 32000000000
  num_cpus: 8
  num_gpus: 1
  object_store_memory: 16000000000
research_design:
  baseline_methods:
  - rule_based_diffusion
  - centralized_attention
  - ablation_2d_pheromone
  num_runs: 3
  performance_metrics:
  - shannon_entropy
  - learning_convergence_speed
  - communication_overhead
  - network_load
  - information_transfer_efficiency
  statistical_analysis:
    confidence_interval: 0.95
    significance_level: 0.05
    test_type: t_test
