# 실험 전반에 대한 설정
experiment:
  name: "DigitalPheromoneMAS_Research"
  log_dir: "results/"
  device: "cuda:0"
  save_interval: 50 # 체크포인트 저장 주기

# 시뮬레이션 환경 설정 (연구 계획서 명시)
environment:
  map_size: [50, 50] # H, W - 맵 크기
  num_agents: 10  # 기본 에이전트 수 (10, 500 확장 예정)
  max_timesteps: 100

# 페로몬 관련 설정 (연구 계획서 명시)
pheromone:
  decay_rate: 0.999 # 시계열 감쇠 기반 확산 모델 (0.995 -> 0.999로 변경하여 더 오래 유지)
  dimensions:
    behavior: 4  # 행동 차원
    emotion: 5   # 감정 차원 (5가지 정서)
    social: 10   # 사회관계 차원
    context: 5   # 환경맥락 차원
  lifecycle: # 페로몬 수명 관리 설정
    min_magnitude_threshold: 0.005  # 0.01 -> 0.005로 감소
    max_lifetime_seconds: 180.0  # 120.0 -> 180.0으로 증가
  
# 어텐션 네트워크 관련 설정 (연구 계획서 명시)
attention:
  embed_dim: 64 # 임베딩 차원 (에이전트 인코더 출력과 일치)
  num_heads: 8    # 멀티-헤드 어텐션 (H∈{4,8})
  topology_type: "full"  # 분산 어텐션 라우팅 네트워크
  
# 학습 및 시뮬레이션 하이퍼파라미터 (연구 계획서 명시)
hyperparameters:
  communication_period: [1, 5] # 통신 주기 τ∈{1,5}
  learning_rate: [0.001, 0.0001] # 학습률 η∈[1e−4,1e−2]
  batch_size: [16, 32] # 배치 크기 B∈{16,32}
  train_networks: true  # 네트워크 학습 활성화
  training_frequency: 10  # N 타임스텝마다 학습 수행
  # 연구 계획서 명시 하이퍼파라미터
  alpha: [0.1, 0.3, 0.5]  # α∈{0.1,0.3,0.5}
  beta: [0.1, 0.3, 0.5]   # β∈{0.1,0.3,0.5}

# 모니터링 및 로깅 설정 (연구 계획서 명시)
monitoring:
  use_wandb: False
  log_frequency: 50 # N 타임스텝마다 시각화 및 로그 기록
  # 연구 계획서 명시 지표들
  track_communication_overhead: true
  track_network_load: true
  track_computation_overhead: true
  track_information_transfer_efficiency: true
  track_learning_convergence: true
  track_attention_entropy: true
  track_pheromone_diffusion_rate: true
  track_agent_cooperation: true
  track_social_network_density: true
  track_environmental_adaptation: true

# 메모리 관리 설정  
memory_management:
  max_memory_percent: 85.0      # 최대 허용 메모리 사용률
  warning_memory_percent: 75.0  # 경고 메모리 사용률
  cleanup_threshold_percent: 80.0 # 자동 정리 시작 임계값
  memory_monitor_interval: 50   # 메모리 모니터링 간격 (타임스텝)

# 연구 계획서 명시 실험 설계
research_design:
  # 비교 대상
  baseline_methods: ["rule_based_diffusion", "centralized_attention"]
  # 성능 지표
  performance_metrics: ["shannon_entropy", "learning_convergence_speed", "communication_overhead", "network_load"]
  # 통계 분석
  statistical_analysis:
    significance_level: 0.05  # α=0.05
    test_type: "t_test"
    confidence_interval: 0.95
  # 반복 실행
  num_runs: 1  # 10회 반복 실행
