# 실험 전반에 대한 설정
experiment:
  name: "DigitalPheromoneMAS_Base"
  log_dir: "results/"
  device: "cuda:0"
  save_interval: 100 # 체크포인트 저장 주기

# 시뮬레이션 환경 설정
environment:
  map_size: [50, 50] # H, W - 맵 크기 축소로 밀도 증가
  num_agents: 10  # 에이전트 수 조정을 통해 리소스 사용량 감소
  max_timesteps: 1000

# 페로몬 관련 설정
pheromone:
  decay_rate: 0.995 # 확산 모델의 감쇠 인자 더욱 완화 (0.98 -> 0.995)
  dimensions:
    behavior: 4
    emotion: 5
    social: 10
    context: 5
  lifecycle: # 페로몬 수명 관리 설정
    min_magnitude_threshold: 0.01 # 임계값 완화 (0.05 -> 0.01)
    max_lifetime_seconds: 120.0    # 수명 대폭 연장 (30 -> 120초)
  
# 어텐션 네트워크 관련 설정
attention:
  embed_dim: 32 # 각 에이전트/페로몬 벡터의 임베딩 차원
  num_heads: 8    # 멀티-헤드 어텐션의 헤드 수
  topology_type: "full"  # full, ring, random
  
# 학습 및 시뮬레이션 하이퍼파라미터
hyperparameters:
  communication_period: [10] # N 타임스텝마다 통신 실행 - 매 스텝 통신
  learning_rate: [0.001, 0.0001]
  batch_size: [32]
  train_networks: true  # 네트워크 학습 활성화
  training_frequency: 10  # N 타임스텝마다 학습 수행

# 모니터링 및 로깅 설정
monitoring:
  use_wandb: False
  log_frequency: 200 # N 타임스텝마다 시각화 및 로그 기록

# 메모리 관리 설정  
memory_management:
  max_memory_percent: 85.0      # 최대 허용 메모리 사용률
  warning_memory_percent: 75.0  # 경고 메모리 사용률
  cleanup_threshold_percent: 80.0 # 자동 정리 시작 임계값
  memory_monitor_interval: 50   # 메모리 모니터링 간격 (타임스텝)
